name: Mirror Clang AOSP

on:
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Download
        run: |
          mkdir clang-download
          cd clang-download
          git init
          git remote add origin https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86
          
          git config core.sparseCheckout true
          echo "clang-r596125/*" >> .git/info/sparse-checkout
          
          git fetch --depth 1 origin af3fae2c8e67673c43217d0cf75dbf3f268de272
          git checkout af3fae2c8e67673c43217d0cf75dbf3f268de272

      - name: Tar.gz
        run: |
          cd clang-download
          tar -czf ../clang-r596125.tar.gz clang-r596125
          cd ..
          ls -lh clang-r596125.tar.gz

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: clang-22-r596125
          name: AOSP Clang 22 (r596125)
          body: |
            Mirror Source Clang Android Google Source.
            Commit Hash: af3fae2c8e67673c43217d0cf75dbf3f268de272
          draft: false
          prerelease: false
          files: |
            clang-r596125.tar.gz
